# The Docker image that will be used to build your app
image: node:lts

test-can-build:
  stage: build
  script:
    - npm ci
    - npm run build
    # npm run build should run without errors, checking types and linting
